services:
  esa-snap-insar:
    build:
      context: .
    volumes:
      - ./:/workspace
      - vscode-extensions:/root/.vscode-server/extensions/
    tty: true
    working_dir: /workspace
    environment:
      - PRIMARY_SAR_PATH: /workspace/data/S1A_IW_SLC__1SDV_20230909T043101_20230909T043131_050246_060C59_F033.SAFE.zip 
      - SECONDARY_SAR_PATH: /workspace/data/S1A_IW_SLC__1SDV_20230921T043101_20230921T043131_050421_061248_FE11.SAFE.zip

volumes:
  vscode-extensions: